services:
  db:
    image: mongo:4.4.13
    networks:
      net_A:
        aliases:
          - db
    env_file:
      - .env

  server:
    build: ./server
    depends_on:
      - db
    ports:
      - "3003:8080"
    networks:
      - net_A
    healthcheck:
      test: curl -f localhost:3003
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  net_A:
    external: false
