services:
  web:
    build: .
    ports:
      - "8080:8080"

  mongo:
    image: mongo:4.4.19
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
