services:
  redis:
    image: redis/redis-stack-server:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=pass456
      - POSTGRES_DB=docker
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 1s
      start_period: 2s
      retries: 5

  nginx:
    image: nginx
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    ports:
      - "80:80"

  web:
    build: ./web
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    external: false
